/**
* @description Trigger handler for Job Leads
**/
public with sharing class JobLeadTriggerHandler  extends TriggerHandler{
    
    /**
	* @description Function to handle the after update  trigger event
	**/
	public override void afterInsert() {
		SharingHelper.manageSharing(
            TR1__Job_Leads__c.sObjectType.getDescribe().getName(),
            Trigger.new,
            null,
            SharingHelper.TriggerContext.RECORDCREATE
        );
	}
    
    /**
	* @description Function to handle the after update  trigger event
	**/
	public override void afterUpdate() {
        system.debug('SIMON JobLeadTrigger TRIGGER Handler executed');
		SharingHelper.manageSharing(
            TR1__Job_Leads__c.sObjectType.getDescribe().getName(),
            Trigger.new,
            Trigger.oldMap,
            SharingHelper.TriggerContext.RECORDUPDATE
        );
	}
}